# Generated by Django 5.2 on 2025-04-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='About Us', max_length=255)),
                ('sous_titre', models.CharField(default='Home > About', max_length=255)),
                ('image_fond', models.ImageField(blank=True, null=True, upload_to='about/header/')),
            ],
        ),
    ]
