# Generated by Django 5.2 on 2025-04-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sous_titre', models.CharField(default='Since 1905', max_length=100)),
                ('titre', models.CharField(max_length=255)),
                ('paragraphe_1', models.TextField()),
                ('paragraphe_2', models.TextField()),
                ('nombre_annees', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_principal', models.CharField(max_length=255)),
                ('texte_bouton_1', models.CharField(max_length=100)),
                ('texte_bouton_2', models.CharField(max_length=100)),
                ('image_background', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
        ),
        migrations.CreateModel(
            name='IntroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
