# Generated by Django 5.2 on 2025-11-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_produit_approuve_produit_vendeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='rejete',
            field=models.BooleanField(default=False),
        ),
    ]
