# Generated by Django 5.2 on 2025-11-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('vendeur', 'Vendeur'), ('admin', 'Admin')], default='vendeur', max_length=50),
        ),
    ]
