# Generated by Django 5.2 on 2025-04-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Blog', max_length=255)),
                ('sous_titre', models.TextField(default='Home > Blog')),
                ('image_fond', models.ImageField(blank=True, null=True, upload_to='blog/headers/')),
            ],
        ),
    ]
